api_version = "2025-01"

[[extensions]]
name = "Free gift quantity rule"
handle = "cart-checkout-validation"
type = "function"

description = "Free gift quantity should not greater then one."

  [[extensions.targeting]]
  target = "purchase.validation.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

